assets:
  config.yml: denistreshchev/home#assets/CodeLonia/prod.json
  id_rsa: denistreshchev/home#assets/heroku-key
  id_rsa.pub: denistreshchev/home#assets/heroku-key.pub
install: |-
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
merge:
  script: |-
    npm install
    npm run build-rultor
deploy:
  script: |-
    echo There is nothing to deploy
    exit 1
release:
  script: |-
    sudo npm run build
    git remote add dokku dokku@dokku.CodeLonia.org:CodeLonia
    rm -rf ~/.ssh
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git fetch
    sed -i "s/0\.0\.0/${tag}/g" ./package.json
    git add ./package.json
    git commit -m 'build number set'
    cp ../prod.json resources/
    git add resources/prod.json
    git commit -m 'prod.json'
    git push -f dokku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    npm run liquibase-prod
    rm -rf resources/prod.json
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 https://www.CodeLonia.org > /dev/null
