language: java
node_js:
  - lts/*
jdk:
  - oraclejdk8
services:
  - docker
install: |-
  npm ci
  npm install -g codecov
script: |-
  set -e
  npm run build-test
  ./node_modules/.bin/nyc report --reporter=lcov
  codecov
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  echo $'Commit message: '$TRAVIS_COMMIT_MESSAGE
  echo $'**Change log:**<br/>'${log//$'\n'/<br/>}
branches:
  only:
    - master
